nextjs:
  replicasCount: 1
  image:
    repository: ""
    tag: "latest"
    pullPolicy: "IfNotPresent"
  ports:
    - name: http
      containerPort: 3000
  resources:
    requests:
      cpu: "100m"
      memory: "256Mi"
    limits:
      cpu: "500m"
      memory: "1Gi"
  autoscaling:
    enabled: true
    minReplicas: 1
    maxReplicas: 5
    targetCPUUtilizationPercentage: 80
    targetMemoryUtilizationPercentage: 80