apiVersion: apps/v1
kind: Deployment
metadata:
  name: express-deployment
spec:
  replicas: {{ .Values.http-backend.replicasCount }}
  selector:
    matchLabels:
      app: express
  template:
    metadata:
      labels:
        app: express
    spec:
      containers:
        - name: express
          image: {{ .Values.http-backend.image.repository }}:{{ .Values.http-backend.image.tag }}
          ports:
            - containerPort: {{ .Values.http-backend.ports.containerPort }}
