apiVersion: v1
kind: Service
metadata:
  name: express-service
spec:
  selector:
    app: express
  ports:
    - protocol: TCP
      port: {{ .Values.express.ports[0].containerPort }}
      targetPort: {{ .Values.express.ports[0].containerPort }}
  type: ClusterIP
