apiVersion: v1
kind: Service
metadata:
  name: express-service
spec:
  selector:
    app: express
  ports:
    - protocol: TCP
      name: {{ .Values.express.ports[0].name }}
      port: {{ .Values.express.ports[1].port }}
      targetPort: {{ .Values.express.ports[2].containerPort }}
  type: ClusterIP

