
FROM node:22-alpine AS deps
WORKDIR /app
COPY . .
RUN pnpm install 

FROM node:22-alpine AS builder
WORKDIR /app

COPY --from=deps /app /app

RUN pnpm turbo run build --filter=./apps/worker-node


FROM node:22-alpine AS runner
WORKDIR /app
COPY --from=builder /app /app
EXPOSE 3000

CMD ["pnpm", "run", "start"]
