apiVersion: v1
kind: Service
metadata:
  name: redis-service
spec:
  selector:
    app: redis
  ports:
    - protocol: TCP
      port: {{ .Values.redis.ports.port }}
      targetPort: {{ .Values.redis.ports.containerPort }}