apiVersion: v1
kind: Service
metadata:
  name: nextjs-service
spec:
  selector:
    app: nextjs
  ports:
    - protocol: TCP
      port: {{ .Values.nextjs.ports[0].port }}
      targetPort: {{ .Values.nextjs.ports[1].containerPort }}
type: ClusterIP