apiVersion: v1
kind: Service
metadata:
  name: nextjs-service
spec:
  selector:
    app: nextjs
  ports:
    - protocol: TCP
      name: {{ .Values.nextjs.ports[0].name }}
      port: {{ .Values.nextjs.ports[1].port }}
      targetPort: {{ .Values.nextjs.ports[2].containerPort }}
type: ClusterIP