apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}-deployment
  labels:
    app: {{ .Chart.Name }}
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  replicas: {{ .Values.worker.replicasCount }}
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: {{ .Values.worker.image.repository }}:{{ .Values.worker.image.tag | default .Chart.AppVersion | quote }}
          imagePullPolicy: {{ .Values.worker.image.pullPolicy }}
          ports:
            - name: {{ .Values.worker.ports[0].name }}
              port: {{ .Values.worker.ports[1].port }}
              containerPort: {{ .Values.worker.ports[2].containerPort }}
          resources:
            {{- toYaml .Values.worker.resources | nindent 12 }}
          env:
            - name: RABBITMQ_URL
              valueFrom:
                secretKeyRef:
                  name: global-secrets
                  key: RABBITMQ_URL
            - name: NODE_ENV
              valueFrom:
                secretKeyRef:
                  name: global-secrets
                  key: NODE_ENV
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: global-secrets
                  key: DATABASE_URL