apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}-service
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: {{ .Chart.Name }}
  ports:
    - protocol: TCP
      name: {{ .Values.worker.ports[0].name }}  
      port: {{ .Values.worker.ports[1].port }}
      targetPort: {{ .Values.worker.ports[2].containerPort }}
  type: ClusterIP