apiVersion: v1
kind: Ingress
metadata:
  name: nginx-ingress
spec:
  rules:
    - host: sitewatch.suvidhaportal.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: nextjs-service
                port:
                  number: 3000 
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: express-service
                port:
                  number: 3001