apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: global-secrets
  namespace: backend  # Change this to your target namespace
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"  # Allows access from any namespace
    argocd.argoproj.io/sync-wave: "-5" 
spec:
  encryptedData:
    # Example: DATABASE_URL (you'll replace this with your actual sealed secret)
    # To create a sealed secret, use:
    # kubeseal --format yaml --cert=public-key.pem < secret.yaml > sealed-secret.yaml
    DATABASE_URL: "YOUR_ENCRYPTED_DATABASE_URL"
    RABBITMQ_URL: "YOUR_ENCRYPTED_RABBITMQ_URL"
  template:
    metadata:
      name: global-secrets
      namespace: backend  # Same as above
    type: Opaque
