worker:
  replicasCount: 1
  image:
    repository: ""
    tag: "latest"
    pullPolicy: "IfNotPresent"
  ports:
    - name: http
      port: 3002
      containerPort: 3002
  resources:
    requests:
      cpu: "200m"
      memory: "512Mi"
    limits:
      cpu: "1000m"
      memory: "2Gi"
  autoscaling:
    enabled: true
    minReplicas: 1
    maxReplicas: 5
    targetCPUUtilizationPercentage: 70
    targetMemoryUtilizationPercentage: 70