apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}-service
spec:
  selector:
    app: {{ .Chart.Name }}
  ports:
    - protocol: TCP
      name: {{ .Values.rabbitmq.ports.name }}
      port: {{ .Values.rabbitmq.ports.port }}
      targetPort: {{ .Values.rabbitmq.ports.containerPort }}
  type: ClusterIP