apiVersion: v1
kind: Service
metadata:
  name: rabbitmq-service
spec:
  selector:
    app: rabbitmq
  ports:
    - protocol: TCP
      port: {{ .Values.rabbitmq.ports.port }}
      targetPort: {{ .Values.rabbitmq.ports.containerPort }}