name: Build and Deploy Backend

on:
  push:
    paths:
      - .github/workflows/http-backend.yaml
      - 'docker/**'
      - 'apps/backend/http-backend/**'
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      
      - name: Docker login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./docker/Dockerfile.http-backend
          push: true
          tags: ring0exec/http-backend:${{ github.sha }}
          build-args: |
            DATABASE_URL=${{ secrets.DATABASE_URL }}

      - name: Clone gitops repo, update, and push
        env:
          PAT: ${{ secrets.GITOPS_TOKEN }}
        run: |
          git clone https://github.com/Torque-Lab/mointering-gitops.git
          cd mointering-gitops
          ls apps/backend/
          cat apps/backend/http-backend.yaml
          sed -i '/name: image.tag/{n;s/value:.*/value: '"${{ github.sha }}"'/}' apps/backend/http-backend.yaml

          git config user.name "GitHub Actions Bot"
          git config user.email "actions@github.com"

            git diff --quiet || {
            git add apps/backend/http-backend.yaml
            git commit -m "Update http-backend image to ${{ github.sha }}"
            git push https://${PAT}@github.com/Torque-Lab/mointering-gitops.git main
          }